### ISSUE TITLE
forum bikeradar cookie consent

### ISSUE THREAD

**Issue by mortyam** [AdguardTeam/AdguardFilters#127303]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

Other ad blocker

### AdGuard version

AdGuard filter lists

### What type of problem have you encountered?

Annoyances — pop-ups, cookie warnings, etc.

### Which browser(s) do you use?

Firefox

### Which device do you use?

Desktop

### Where is the problem encountered?

https://forum.bikeradar.com/

### What filters do you have enabled?

AdGuard Social Media filter, AdGuard Annoyances filter

### Add your comment and screenshots

1. <comment>

2. Screenshots
<details><summary>Screenshot 1:</summary>

</details>

<details><summary>Screenshot N:</summary>

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Sergey-Lyapin** [comment]
Unfortunately, we cannot reproduce the issue with your settings.

Please try checking the filters updates, maybe it was already solved. If you’re still able to reproduce the issue, reopen it here. We’d appreciate if you supply additional information or screenshots.

**Comment by mortyam** [comment]
@Sergey-Lyapin Hello, I will try to give some details that maybe will help in solving the problem:
-OS: Windows 10 Pro 64bit
-Browser: Microsoft Edge 104.0.1293.54/ Firefox 103.0.2
-ad-block: Ublock Origin 1.44
-Ad-Guard filters: AD-Guard Annoyance and Ad-Guard Social

All filters are up-to-date but I still see this pop-up. Here is:
![Capture](https://user-images.githubusercontent.com/47023431/185174222-1aebd0cc-8073-4bd9-9a12-9e049a014a3f.PNG)

**Comment by Sergey-Lyapin** [comment]
Hi @mortyam
Fixed now, thanks.
