### ISSUE TITLE
adservice.google.com [DNS] [Android]

### ISSUE THREAD

**Issue by Nzzyme** [AdguardTeam/AdguardFilters#71165]
Observed this sneaked through when doing a search in Chrome for Android. Please block. Checked with AG for Android.

**Comment by seyoon20087** [comment]
This rule will be added soon in `MobileFilters/sections/adservers.txt`:
```
! https://github.com/AdguardTeam/AdguardFilters/issues/71165
||adservice.google.com^
```

**Comment by Nzzyme** [comment]
Ok, and why not in AdGuard DNS filter?

**Comment by seyoon20087** [comment]
> Ok, and why not in AdGuard DNS filter?

You can add this rule if you have access to AdGuard for Android:
```
! https://github.com/AdguardTeam/AdguardFilters/issues/71165
||adservice.google.com^
```

**Comment by Alex-302** [comment]
@Nzzyme where is it not blocked?

**Comment by Alex-302** [comment]
It is also blocked by DNS
![image](https://user-images.githubusercontent.com/8361299/104221909-419c2f80-544a-11eb-85e7-b96299ca05a0.png)

**Comment by Nzzyme** [comment]
I see this in Chrome. Steps for testing:

1. Update AG filters
2. Clear cache, cookies, browsing history in Chrome
3. perform a search with any text string and I see this in the filtering log


![Screenshot-20210112094917](https://user-images.githubusercontent.com/6959116/104269408-3bdf3200-54bc-11eb-94f1-cc2f22630945.jpg)


DNS Filtering is enabled.
DNS Server: AG DNS
DNS Requests blocking: Enabled
AG DNS Filter Enabled
DNS User Filter: 'adservice.google.com' not whitelisted

**Comment by Alex-302** [comment]
0.0.0.0 = blocked

**Comment by Nzzyme** [comment]
I thought that blocked entries in the log have a red color and opening that would have a button which says "Unblock"?

If this is indeed blocked, then why is the color for this entry not red?

**Comment by Alex-302** [comment]
> why is the color for this entry not red?

Because it is blocked on DNS level. App cannot see why domain is resolved with 0.0.0.0 IP.

**Comment by Nzzyme** [comment]
Other 'DNS' entries that are blocked have a red color on them indicating they are blocked but this one does not. That's why I wanted to check.

**Comment by Alex-302** [comment]
> any DNS entry with 0.0.0.0 is blocked

No. 0.0.0.0 can we assigned also by the site owner.

**Comment by Nzzyme** [comment]
![Screenshot_20230617204202](https://github.com/AdguardTeam/AdguardFilters/assets/6959116/f95a08c7-7939-41b3-849c-205f1a0d1409)

Still not added??

**Comment by Alex-302** [comment]
Where?

**Comment by Nzzyme** [comment]
> Where?

[Here](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt)

Since it is a DNS request, shouldn't it be added in the DNS filter?

**Comment by Nzzyme** [comment]
![Screenshot_20230704232726](https://github.com/AdguardTeam/AdguardFilters/assets/6959116/951b6cd0-39fb-450a-a3dd-33108b719a72)


Bump

**Comment by Alex-302** [comment]
It may cause mode anti-adblock issues.
