### ISSUE TITLE
yalujailbreak.net

### ISSUE THREAD

**Issue by LaxusiC** [AdguardTeam/AdguardFilters#7995]
Type: Anti-Adblock

Screenshot: https://imgur.com/a/wbCd6

Filter: Safari, Mobile Ads, Annoyances, English, Spyware

**Comment by AdamWr** [comment]
Could you please check this rule:
`@@||yalujailbreak.net^$elemhide`

**Comment by AdamWr** [comment]
Thank you for your answer.
It's strange, because I checked few "articles" and it works fine on my end with that rule.
Does it work if you disable English filter?

**Comment by LaxusiC** [comment]
@AdamWr i disabled english filter and it still happening, only when i view the article

**Comment by lancelot-moon** [comment]
English filter causes the Anti-adblock.
However, can Adguard Pro for iOS only block the javascript under a normal domain, not a whole domain, such like AdGuard for Android?

**Comment by LaxusiC** [comment]
I only getting it when i'm using iOS Safari, tried resetting history, cookie, etc ... the problem still persist

**Comment by AdamWr** [comment]
@LaxusiC Do you use AdGuard DNS?
If so, could you please disable it and check again (with this rule in user filter - `@@||yalujailbreak.net^$elemhide`)?

@lancelot-moon on Android it is fixed by `JS` rule, which is not supported by iOS.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/33550603-d9bbe344-d8ee-11e7-80bc-7631572644b9.png)

</details>

**Comment by LaxusiC** [comment]
I disabled AGDNS and it worked, is there a way to fix cause i don't want to turn off the vpn

**Comment by AdamWr** [comment]
I'm using AdGuard DNS on my iPad also and I don't have this problem.
Did you add any domain to "blacklist" in AdGuard DNS settings?

These requests must be unblocked otherwise "adblock" will be detected:
<details>

```
ad.mail.ru/favicon1.ico
ads.twitter.com/favicon.ico
advertising.aol.com/favicon.ico
advertising.yahoo.com/favicon.ico
crunchyroll.adclixx.net/vast?fg=
crunchyroll.adnetasia.com/vast?fg=
crunchyroll.adtrackers.net/vast?fg=
crunchyroll.bannertrack.net/vast?fg=
doubleclickbygoogle.com/favicon.ico
google.com/adsense/start/images/favicon.ico
gstatic.com/adx/doubleclick.ico
ox-d.adclixx.net/auid=
ox-d.adnetasia.com/auid=
ox-d.adtrackers.net/auid=
ox-d.bannertrack.net/auid=
partnerads.ysm.yahoo.com/favicon1.ico
serve.adclixx.net/promoload
serve.adnetasia.com/promoload
serve.adtrackers.net/promoload
serve.bannertrack.net/promoload
torrentz.adclixx.net/mgid/ad.js
torrentz.adnetasia.com/mgid/ad.js
torrentz.adtrackers.net/mgid/ad.js
torrentz.bannertrack.net/mgid/ad.js
yahoo.adclixx.net/serv
yahoo.adnetasia.com/serv
yahoo.adtrackers.net/serv
yahoo.bannertrack.net/serv
yasni.adclixx.net/design/relaunch/gfx/elitepartner_
yasni.adnetasia.com/design/relaunch/gfx/elitepartner_
yasni.adtrackers.net/design/relaunch/gfx/elitepartner_
yasni.bannertrack.net/design/relaunch/gfx/elitepartner_
zoover.adclixx.net/shared/bannerpages/darttagsbanner.aspx
zoover.adnetasia.com/shared/bannerpages/darttagsbanner.aspx
zoover.adtrackers.net/shared/bannerpages/darttagsbanner.aspx
zoover.bannertrack.net/shared/bannerpages/darttagsbanner.aspx
```

</details>

**Comment by lancelot-moon** [comment]
Only enable English filter in Safari content blocker.
Don't need to connect to AdGuard DNS.
Still see Anti-adblock after trying to read any articles.
https://imgur.com/a/XtMc6

**Comment by AdamWr** [comment]
@lancelot-moon Did you add that rule to user filter? - `@@||yalujailbreak.net^$elemhide`

**Comment by lancelot-moon** [comment]
After adding @@||yalujailbreak.net^$elemhide in Safari's user filter, no anti-adblock.

**Comment by AdamWr** [comment]
Ok, thank you for checking it :)
I added that rule to `Safari filter`.

**Comment by BlazDT** [comment]
@AdamWr 
Do we still need the exclusion?
