### ISSUE TITLE
Blocking all 88x31 buttons

### ISSUE THREAD

**Issue by climbTheStairs** [AdguardTeam/AdguardFilters#98923]
***Description***:

AdguardFilters blocks 88x31 size images, but many of the times, they are not ads at all.  For example, they are used to [indicate a Creative Commons license](https://creativecommons.org/about/downloads/) or to [display the site owner's favorite tools, memes, beliefs, and interests](https://cyber.dabamos.de/88x31/index.html).

* **Current behaviour**:

All images/buttons that specify size 88x31 in the HTML are hidden by the filter `##img[width="88"][height="31"]` in [AdGuard Tracking Protection](https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/general_elemhide.txt).

<details>
<summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/51103593/140278755-eeedd612-5776-4a26-84f9-4652d5ed2702.png)

![image](https://user-images.githubusercontent.com/51103593/140278792-d4cf3634-b7af-4754-b4ba-8b7594358f8e.png)

</details><br/>

* **Expected behaviour**: 

88x31 images should not blocked by AdGuard

<details>
<summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/51103593/140278560-025871da-6498-455f-9ca6-b90ea21ed702.png)

![image](https://user-images.githubusercontent.com/51103593/140278833-c8d1fc2e-6eff-41b6-b34a-08de1d721030.png)

</details><br/>

***Steps to reproduce the problem***:

1.  Visit any page with 88x31 buttons (e.g. <https://cyber.dabamos.de/88x31/index.html>)
2.  Buttons are hidden :sob:

***System configuration***

**Filters:**

AdGuard Tracking Protection

Information                            | Value
---                                    | ---
Operating system:                      | GNU/Linux
Operating system version (Android/iOS) | N/A
Browser:                               | Firefox
AdGuard version:                       | N/A
Filters enabled:                       | AdGuard Tracking Protection
AdGuard mode (Android only):           | N/A
Filtering quality (Android only):      | N/A
HTTPS filtering (Android only):        | N/A
Simplified filters (iOS only)          | N/A
AdGuard DNS:                           | None
Stealth mode options (Windows only)    | N/A
Helpdesk ID (if exists):               | N/A

[//]: # (This template is meant for missed ad/false positive reports, for other type of reports edit it accordingly)

**Comment by Alex-302** [comment]
Fixed for this site.

**Comment by climbTheStairs** [comment]
The problem isn't only on the site <https://cyber.dabamos.de/88x31/index.html>, which I gave as an example.  That site is simply a collection of 88x31 gifs that are used on many other sites.  Since most 88x31 images are not advertisements or trackers, I suggest removing the filter `##img[width="88"][height="31"]` from <https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/general_elemhide.txt> rather than unblocking them on individual websites.

**Comment by Alex-302** [comment]
Not sure about removing
https://web.archive.org/web/20110701204156/http://www.iab.net/iab_products_and_industry_services/508676/508767/Ad_Unit

**Comment by oatmealine** [comment]
Can confirm this is still reproducible and still a very annoying issue; 88x31 buttons are a relic of the old web and highly popular on sites like neocities.org where people make personal websites and spread around 88x31 buttons of their sites. Found this issue myself specifically while working on my own site (oat.zone) where these buttons are visible under `ls badges`, but I can think of many more personal websites that use them for non-tracking or ad related purposes. (It's common practice to _avoid_ hotlinking buttons, if that's a concern.)

**Comment by climbTheStairs** [comment]
Agreed; while there might be ads that are size 88x31, there are also lots of other images this size that are legitimate content, and it is impossible to determine whether an image is an advertisement solely based on its size.

Regardless, this filter does not block images of this size, but only images with their sizes specified with the `<img>`  `height` and `width` attributes in the HTML.  All someone would need to do to bypass this is to remove these attributes, which hurts user experience.  This filter only discourages people from setting these attributes.
